name: contacts
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+4
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
